#!/usr/bin/env bash
# Fresh migration + full RLS security test run. Exits non-zero on any
# migration error or failed security assertion.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DB_NAME="dayline_rls_test"

bash "${SCRIPT_DIR}/run_migrations.sh" "${DB_NAME}"
echo "--- running RLS security tests ---"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${DB_NAME}" -f "${SCRIPT_DIR}/rls_security.test.sql"
echo "--- running worker job-claim tests ---"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${DB_NAME}" -f "${SCRIPT_DIR}/worker_claim.test.sql"
echo "--- running entitlement archive tests ---"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${DB_NAME}" -f "${SCRIPT_DIR}/entitlement_archive.test.sql"
echo "--- running group timezone tests ---"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${DB_NAME}" -f "${SCRIPT_DIR}/group_timezone.test.sql"
echo "--- running input validation tests ---"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${DB_NAME}" -f "${SCRIPT_DIR}/input_validation.test.sql"
echo "--- running data export tests ---"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${DB_NAME}" -f "${SCRIPT_DIR}/data_export.test.sql"
echo "--- running group role management tests ---"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${DB_NAME}" -f "${SCRIPT_DIR}/group_role_management.test.sql"
echo "--- running comment/reaction rate limit tests ---"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${DB_NAME}" -f "${SCRIPT_DIR}/comment_reaction_rate_limit.test.sql"
echo "--- running group creation rate limit tests ---"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${DB_NAME}" -f "${SCRIPT_DIR}/group_creation_rate_limit.test.sql"
echo "--- running moderator remove content tests ---"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${DB_NAME}" -f "${SCRIPT_DIR}/moderator_remove_content.test.sql"
echo "--- running moderator resolve report tests ---"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${DB_NAME}" -f "${SCRIPT_DIR}/moderator_resolve_report.test.sql"
echo "--- running caption consent revoke tests ---"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${DB_NAME}" -f "${SCRIPT_DIR}/clear_captions_on_consent_revoke.test.sql"
echo "--- running moderator warn user tests ---"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${DB_NAME}" -f "${SCRIPT_DIR}/moderator_warn_user.test.sql"
echo "--- running push token reassignment tests ---"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${DB_NAME}" -f "${SCRIPT_DIR}/push_token_reassignment.test.sql"
echo "--- running rate limit race tests ---"
sudo -u postgres bash "${SCRIPT_DIR}/rate_limit_race.test.sh" "${DB_NAME}"
